# Generated by Django 4.2 on 2023-06-04 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_place",
                    models.CharField(max_length=100, verbose_name="Logradouro"),
                ),
                (
                    "neighborhood",
                    models.CharField(blank=True, max_length=255, verbose_name="Bairro"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=50, verbose_name="Cidade"),
                ),
                ("zip_code", models.IntegerField(verbose_name="CEP")),
                ("number", models.IntegerField(verbose_name="Número")),
                (
                    "complement",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Complemento"
                    ),
                ),
            ],
            options={
                "verbose_name": "Endereço",
                "verbose_name_plural": "Endereços",
            },
        ),
        migrations.CreateModel(
            name="Telephone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=20, verbose_name="Número")),
                ("type", models.CharField(max_length=20, verbose_name="Número")),
            ],
            options={
                "verbose_name": "Telefone",
                "verbose_name_plural": "Telefones",
            },
        ),
        migrations.AddField(
            model_name="client",
            name="birth_date",
            field=models.DateField(null=True, verbose_name="Data de Nascimento"),
        ),
        migrations.AddField(
            model_name="client",
            name="deleted_at",
            field=models.DateTimeField(null=True, verbose_name="Data Delecao"),
        ),
        migrations.AddField(
            model_name="client",
            name="email",
            field=models.CharField(max_length=100, null=True, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="client",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Status"),
        ),
        migrations.AddField(
            model_name="client",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="client",
            name="registered",
            field=models.BooleanField(default=False, verbose_name="Inscrito"),
        ),
        migrations.AddField(
            model_name="client",
            name="subscriber",
            field=models.BooleanField(default=False, verbose_name="Assinante"),
        ),
        migrations.AddField(
            model_name="client",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addressies",
                to="client.address",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="telephone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="telephones",
                to="client.telephone",
            ),
        ),
    ]
