# Generated by Django 4.2 on 2023-06-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_address_telephone_client_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telephone",
            name="type",
            field=models.CharField(
                choices=[("cel", "Celular"), ("fix", "Fixo")],
                max_length=3,
                verbose_name="Número",
            ),
        ),
    ]
