# Generated by Django 4.1.3 on 2023-07-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="registered",
        ),
        migrations.RemoveField(
            model_name="user",
            name="subscriber",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("USE", "Papel do assinante"),
                    ("ADM", "Papel do administrador"),
                ],
                default="USE",
                max_length=10,
                verbose_name="Papel",
            ),
        ),
    ]
